[package]
name = "utils"
authors = ["Hatef Rahmani <rahmani.hatef@gmail.com>"]
version = "0.1.0"
edition = "2024"


[dependencies]
thiserror = "2.0.15"
clap = { version = "4.5.45", features = ["derive", "env"] }
twelf = "0.15.0"
serde = "1.0.219"
const-hex = "1.14.1"
alloy-rpc-types-eth = "1.0.24"
alloy = { version = "1.0.25", features = ["transports"] }
sea-orm = { version = "1.1.14", features = ["sqlx"] }
