[package]
name = "block-scaner"
authors = ["Hatef Rahmani <rahmani.hatef@gmail.com>"]
version = "0.1.0"
edition = "2024"

[[bin]]
name = "server"
path = "bin/app-server.rs"

[[bin]]
name = "indexer"
path = "bin/app-indexer.rs"

[workspace]
members = ["libs/*", "migration"]

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
utils = { version = "0.1.0", path = "libs/utils" }
orm = { version = "0.1.0", path = "libs/orm" }
api = { version = "0.1.0", path = "libs/api" }
indexer = { version = "0.1.0", path = "libs/indexer" }
